export const USER_ID_ESZOBOT = "317421133131677696";
export const CHANNEL_ID_BEEP_BEEP_BOP = "730686599049773086";

export const SUPPORTED_COMMANDS = [
  "!bling",
  "!airhorn",
  "!joeputa",
  "!fgilipollas",
  "!laloli",
  "!salchichonio",
  "!subnormal",
  "!janso",
  "!yaves",
  "!elagua",
  "!augale",
  "!duah",
  "!mishon",
  "!goodjob",
  "!notcool",
  "!showme",
  "!pitorro",
  "!rekt",
  "!omaewa",
  "!jeff",
  "!okay",
  "!wry",
  "!ezmoney",
  "!rapper",
  "!nanimo",
  "!noesbien",
  "!fornai",
  "!puesyose",
  "!incredibilis",
  "!unaceptable",
  "!baka",
  "!nohayclase",
  "!uitheme",
  "!yourway",
  "!complete",
  "!sacala",
  "!lablanca",
  "!porquesacala",
  "!quemando",
  "!yosha",
  "!wide",
  "!nonono",
  "!yoo",
  "!desgraciatis",
  "!mmm",
  "!mipan",
  "!martes",
  "!miercoles",
  "!jueves",
  "!viernes",
  "!marica",
  "!mikoboat",
  "!nigga",
  "!eekumbokum",
  "!xana",
  "!odd",
  "!orale",
  "!hahahaha",
  "!beti",
  "!panpanpan",
  "!noentiendo",
  "!toque",
  "!imin",
  "!eo",
  "!3pingos",
  "!buendia",
  "!palos",
  "!casa",
  "!xokas",
  "!uegh",
  "!30monkeys",
  "!yooo",
  "!maraca",
  "!competente",
  "!discriminando",
  "!israel",
  "!letsgo",
  "!topesperando",
  "!jamas",
  "!mondarina",
  "!3mondarinas",
  "!uno",
  "!tabien",
  "!topenemigo",
  "!sabado",
  "!sisuka",
  "!hando",
  "!platinada",
  "!esigual",
  "!pimiento",
];

export const REGEX = {
  YT: /^!yt /,
  TORB: /(torb)|(enano)|(upgrade)/i,
  WAH: /(luigi)|((w|gu)a+h*)/i,
  // SALUDOS: /(Hola a todos)|(buenas)|(señores?)/i,
  // CARGA: /(carga)|(punto)|(payload)|(proteg)/i,
  // PEPLO: /(pero)|(orisa)|(support)/i,
  // ASCO: /(asco)|(c[aá]ncer)|(sida)|(zanker)|(asquer)|(pharah?)|(yasuo)|(hanzo)/i,
  // RATE: /^(?!http).*[0-9]+\/[0-9]+/,
  // JIROS: /jiro+u*s+/i,
  // CALL_ME: /(c[ao]ll$)|(c[ao]ll )|(cell)|(selfon)|(avis)/i,
  // BORJA: /(borj)|(Hagrov)/i,
  // QUEJA: /((c[aá]lla(te)?)|(que te calles)|(ktkys)|(puto)).*bot/i,
  // STAPH: /(bot staph)|(para bot)/i,
  // NO_LINK: /^(?!http).*/,
  // TSS: /^(\/TTS).*/,
  // EXCLAMATION_START: /^![^ ]*$/,
  // YES_NO: /(s[ií] o no,? bot)|(bot.* s[ií] o no)|(a que (s[ií]|no),? bot)/i,
  // CUANTOS: /(Cu[aá]ntos somos\??)/i,
  // GALE: /[gG]aleginho.*/i,
  // HUM: /hu*m+\b/i,
  // PAGAR: /!pagar [0-9]+ <@![0-9]+>$/i,
  // RIOT_REGISTER: /^!riotRegister .+$/i,
  // BET: /!bet [0-9]+ <@![0-9]+> (gana|pierde)$/,
  // PROGRAMMED_MSG: /!progMsg [0-9]{18} [0-9]+[mMhHsS] .+/i,
  // BAN: /!putoPlatino <@![0-9]+> [0-9]{1,2}/i,
};
